In [1]:
import numpy as np
#Col 0 is weight
#Col 1 is Height
X = np.array(
[[73.847017017515, 241.893563180437],
 [68.7819040458903, 162.3104725213],
 [74.1101053917849, 212.7408555565],
 [71.7309784033377, 220.042470303077],
 [69.8817958611153, 206.349800623871],
 [67.2530156878065, 152.212155757083],
 [68.7850812516616, 183.927888604031],
 [68.3485155115879, 167.971110489509],
 [67.018949662883, 175.92944039571],
 [63.4564939783664, 156.399676387112]]
)

In [2]:
X.shape

(10, 2)

In [16]:
lst = []
for i in X:
    lst.append(i[0])
    
np.mean(lst)

69.32138568119487

In [31]:
#All Rows From Col 0
print(X[:, 0])
#Mean Weight
weight_bar = np.mean(X[:, 0])

[73.84701702 68.78190405 74.11010539 71.7309784  69.88179586 67.25301569
 68.78508125 68.34851551 67.01894966 63.45649398]


In [19]:
#weight and height of second person
print(X[1, :])

[ 68.78190405 162.31047252]


In [30]:
#All Rows From Col 1
print(X[:, 1])
#Mean Hight
height_bar = np.mean(X[:, 1])

[241.89356318 162.31047252 212.74085556 220.0424703  206.34980062
 152.21215576 183.9278886  167.97111049 175.9294404  156.39967639]


In [26]:
#All Rows From Col 1
print(X[:5, 1])
#Mean Hight
np.mean(X[:5, 1])

[241.89356318 162.31047252 212.74085556 220.0424703  206.34980062]


208.667432437037

In [29]:
#Weight of the 9th person
X[8, 0]

67.018949662883

In [41]:
#subtract mean from corresponding cols
print("weight - mean:\n", X[:, 0] - weight_bar)

print("\n")

print("height - mean:\n", X[:, 1] - height_bar)

weight - mean:
 [ 4.52563134 -0.53948164  4.78871971  2.40959272  0.56041018 -2.06836999
 -0.53630443 -0.97287017 -2.30243602 -5.8648917 ]


height - mean:
 [ 53.9158198  -25.66727086  24.76311217  32.06472692  18.37205724
 -35.76558762  -4.04985478 -20.00663289 -12.04830299 -31.57806699]


In [43]:
X - np.mean(X, axis=0)

array([[  4.52563134,  53.9158198 ],
       [ -0.53948164, -25.66727086],
       [  4.78871971,  24.76311217],
       [  2.40959272,  32.06472692],
       [  0.56041018,  18.37205724],
       [ -2.06836999, -35.76558762],
       [ -0.53630443,  -4.04985478],
       [ -0.97287017, -20.00663289],
       [ -2.30243602, -12.04830299],
       [ -5.8648917 , -31.57806699]])

In [47]:
X - np.mean(X, axis=1)

ValueError: operands could not be broadcast together with shapes (10,2) (10,) 

In [48]:
#This is meaningless for our dataset
np.mean(X, axis=1)

array([157.8702901 , 115.54618828, 143.42548047, 145.88672435,
       138.11579824, 109.73258572, 126.35648493, 118.159813  ,
       121.47419503, 109.92808518])

In [62]:
A = np.array([[1,2],[3,4]])
print(A)
print(np.sum(A))  #compute sum of all elements
#Axis 0 is for Col
print(np.sum(A,axis=0)) #compute su of each column
#Axis 1 is for Row
print(np.sum(A,axis=1))  #compute sum of each row

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [69]:
V = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(V)
print()
#vector from V
print("Vector of Col", V[:,0])
print("Vector of Row", V[1,:])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Vector of Col [ 1  4  7 10]
Vector of Row [4 5 6]
