In [9]:
import numpy as np
A = np.array([[1,2],[0,1],[2,3]])
V = np.array([[2],[6]])
print("_Matrix A_\n", A)
print("_Vector V_\n", V)
print("_Dot product of A and V_\n", np.dot(A,V))

_Matrix A_
 [[1 2]
 [0 1]
 [2 3]]
_Vector V_
 [[2]
 [6]]
_Dot product of A and V_
 [[14]
 [ 6]
 [22]]


In [11]:
B = np.array([[5],[7]])
print("_Vector B_\n", B)
print("_Dot product of A and B_\n", np.dot(A,B))

_Vector B_
 [[5]
 [7]]
_Dot product of A and B_
 [[19]
 [ 7]
 [31]]


In [17]:
C = np.array([[2,5],[6,7]])
print("_Matrix A_\n", A)
print("_Matrix C_\n", C)
print("_Dot product of A and C_\n", np.dot(A,C))

_Matrix A_
 [[1 2]
 [0 1]
 [2 3]]
_Matrix C_
 [[2 5]
 [6 7]]
_Dot product of A and C_
 [[14 19]
 [ 6  7]
 [22 31]]


In [24]:
print(np.dot(C, A))

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [28]:
new_A = np.array([[1,2],[0,1]])
print("_Matrix new_A_\n", new_A)
print("_Matrix C_\n", C)
print("_Dot product of new_A and C_\n", np.dot(C, new_A))

_Matrix new_A_
 [[1 2]
 [0 1]]
_Matrix C_
 [[2 5]
 [6 7]]
_Dot product of new_A and C_
 [[ 2  9]
 [ 6 19]]


In [34]:
Identity = np.array([[1,0],[0,1]])
print("_Matrix A_\n", new_A)
print("_Matrix Identity_\n", Identity)
print("_Dot product of new_A*Identity == Identity*new_A is Ture _\n", np.dot(Identity, new_A) == np.dot(new_A, Identity))

_Matrix A_
 [[1 2]
 [0 1]]
_Matrix Identity_
 [[1 0]
 [0 1]]
_Dot product of new_A*Identity == Identity*new_A is Ture _
 [[ True  True]
 [ True  True]]


In [36]:
import matplotlib.pyplot as plt

# Running Distance in Mile
x = np.array([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
                         7.042,10.791,5.313,7.997,5.654,9.27,3.1])

# Water Drinks in Litre
y = np.array([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,
                         2.827,3.465,1.65,2.904,2.42,2.94,1.3])

w1 = 0.25163494 
w0 = 0.79880123 
y_pred = [w1*i + w0 for i in x]
print(y_pred)

[1.629196532, 1.905994966, 2.1827934, 2.4872716774, 2.5426313642, 1.84761565992, 3.25953930826, 2.3544084290800003, 2.7087104245999996, 1.34409414498, 2.57081447748, 3.51419386754, 2.13573766622, 2.81112584518, 2.2215451807599997, 3.1314571237999997, 1.578869544]


In [50]:
# print(np.ones((len(x), 1)))
# print(np.transpose([x]))
# Concatenate two matrix column-wise 
X = np.concatenate((np.transpose([x]), np.ones((len(x), 1))), axis=1)
# print(X)
print(X.T)

[[ 3.3    4.4    5.5    6.71   6.93   4.168  9.779  6.182  7.59   2.167
   7.042 10.791  5.313  7.997  5.654  9.27   3.1  ]
 [ 1.     1.     1.     1.     1.     1.     1.     1.     1.     1.
   1.     1.     1.     1.     1.     1.     1.   ]]


In [38]:
w = np.array([w1, w0])

In [39]:
np.dot(X, w)

array([1.62919653, 1.90599497, 2.1827934 , 2.48727168, 2.54263136,
       1.84761566, 3.25953931, 2.35440843, 2.70871042, 1.34409414,
       2.57081448, 3.51419387, 2.13573767, 2.81112585, 2.22154518,
       3.13145712, 1.57886954])

In [53]:
T = np.array([[1,2,3],[4,5,6]])
print(T)
print("_transposed_\n", T.T)

[[1 2 3]
 [4 5 6]]
_transposed_
 [[1 4]
 [2 5]
 [3 6]]


In [54]:
from numpy import linalg as LA
v = np.array([3, 4])
LA.norm(v)

5.0

In [55]:
v = np.array([3, 4])
np.sqrt(np.dot(v,v.T))

5.0

In [56]:
u = np.array([3, 4])
v = np.array([6, 1])
print(LA.norm(u - v))

4.242640687119285


In [57]:
u = np.array([1, 1])
v = np.array([2, 2])
r = np.array([3, 8])
print(LA.norm(u - v))
print(LA.norm(u - r))
print(LA.norm(v - r))

1.4142135623730951
7.280109889280518
6.082762530298219
